language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
services:
  - mysql
  - redis-server
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Initialization, Database
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dp_node;'
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  # Run test script, depending on istanbul install
  - "test ! -z $(npm -ps ls istanbul) || npm test"
