language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
services:
  - mysql
  - redis-server
sudo: false
before_install:
  # Initialization, Database
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dp_node;'
script:
  # Run test script, depending on istanbul install
  - "npm test"
