environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "12"
services:
  - mysql
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - if exist node_modules npm prune
  - if exist node_modules npm rebuild
  - npm -v
  - node -v
  - SET PATH=C:\Program Files\MySql\MySQL Server 5.7\bin\;%PATH%
  - npm install
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
build: off
before_test:
  - mysql -uroot -pPassword12! -e "CREATE DATABASE IF NOT EXISTS dp_node;"
test_script:
  - node --version
  - npm --version
  - npm run test
version: "{build}"
